apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
  labels:
    app: myapp
  annotations:
    argocd.argoproj.io/instance: myapp-argo-application
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: dumalaramesh/hiring-app:24
        ports:
        - containerPort: 8080
