apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp
  labels:
    app: myapp
  annotations:
    argocd.argoproj.io/instance: myapp-argo-application
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 9000
      targetPort: 8080
  selector:
    app: myapp
